### PR TITLE
docs: Adapted README to Node-SDK

### PR DESCRIPTION
**Pull request by LorenzNickel**
Reorganzied README to match with the [NodeJS-SDK](https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/blob/2.0.x/README.md)

## Description
Put things in the order and named it the way they are in the Node-SDK.

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] My code follows the code style of this project
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [x] I have read the **README** document
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

## License

- [x] By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.

[issues]: https://github.com/alexa/alexa-skills-kit-sdk-for-java/issues
[license]: http://aws.amazon.com/apache2.0/
[cla]: http://en.wikipedia.org/wiki/Contributor_License_Agreement

### CODE REVIEW

**Comment by LorenzNickel** [comment]
I was not sure if [Location Services](https://developer.amazon.com/docs/custom-skills/location-services-for-alexa-skills.html) are supported by THIS SDK, if so another commit would be needed to add them to the ReadMe.

**Comment by LorenzNickel** [comment]
I was not sure if [Location Services](https://developer.amazon.com/docs/custom-skills/location-services-for-alexa-skills.html) are supported by THIS SDK. If so another commit would be needed to add them to the ReadMe.

**Review by LorenzNickel — COMMENTED** [review]
Discussed [here](https://github.com/alexa/alexa-skills-kit-sdk-for-nodejs/pull/523#discussion_r263094902)

**Comment by breedloj** [comment]
Hey, thanks for the contribution! I am all for consistency in our landing pages so this is a cool change. Will go ahead and merge this in -- thanks again!

**Pull request merged**
