### PR TITLE
Added slot entity resolution

### PR DESCRIPTION
**Pull request by sebastiande**
I've added slot entity resolution classes to deserialize the json and have access to the fields.

### CODE REVIEW

**Comment by Saandji** [comment]
it is possible somehow to use your version without waiting for it to be released?

**Comment by sebastiande** [comment]
sure, just checkout my branch and run "mvn clean deploy" to deploy it to your local repository.

**Comment by jeromeernestgarcia** [comment]
I downloaded your branch, navigated to the root of the directory structure, and ran "mvn clean deploy". I got the following failure. Any suggestions?

[INFO] --- maven-install-plugin:2.4:install (default-install) @ alexa-skills-kit ---
[INFO] Installing /Users/jeromegarcia/alexa-skills-kit-java-masterSebastianBranch/target/alexa-skills-kit-1.5.1-SNAPSHOT.jar to /Users/jeromegarcia/.m2/repository/com/amazon/alexa/alexa-skills-kit/1.5.1-SNAPSHOT/alexa-skills-kit-1.5.1-SNAPSHOT.jar
[INFO] Installing /Users/jeromegarcia/alexa-skills-kit-java-masterSebastianBranch/pom.xml to /Users/jeromegarcia/.m2/repository/com/amazon/alexa/alexa-skills-kit/1.5.1-SNAPSHOT/alexa-skills-kit-1.5.1-SNAPSHOT.pom
[INFO] 
[INFO] --- maven-deploy-plugin:2.7:deploy (default-deploy) @ alexa-skills-kit ---
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 2.303 s
[INFO] Finished at: 2017-10-02T14:30:37-07:00
[INFO] Final Memory: 19M/331M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-deploy-plugin:2.7:deploy (default-deploy) on project alexa-skills-kit: Deployment failed: repository element was not specified in the POM inside distributionManagement element or in -DaltDeploymentRepository=id::layout::url parameter -> [Help 1]
[ERROR]

**Comment by brendanclement** [comment]
Hey @sebastiande & @Saandji . We've added entity resolution to 1.6.0 of alexa-skills-kit package.

If you modify your POM to target 1.6.0 then you can make use of these features.

**Comment by sebastiande** [comment]
Hey @jeromeernestgarcia Sorry i meant mvn clean install. But now you simply can use the official release. Thank you @brendanclement

**Pull request closed without merging**
