### PR TITLE
Handle null directive properly

### PR DESCRIPTION
**Pull request by kkocel**
Handle null directive properly in ResponseBuilder

## Description
Checking if directive is not null

## Motivation and Context
Makes API more resilient for invalid input

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [x] My code follows the code style of this project
- [ ] My change requires a change to the documentation
- [ ] I have updated the documentation accordingly
- [x] I have read the **README** document
- [x] I have added tests to cover my changes
- [x] All new and existing tests passed

## License

- [ ] I confirm that this pull request can be released under the Apache 2 license

[issues]: https://github.com/alexa/alexa-skills-kit-sdk-for-java/issues
[license]: http://aws.amazon.com/apache2.0/
[cla]: http://en.wikipedia.org/wiki/Contributor_License_Agreement

### CODE REVIEW

**Comment by breedloj** [comment]
Hey Christopher, thanks for the PR. A couple of questions/comments: while I am all for writing defensive code, I am not sure that in practice this change accomplishes much. A null card being attached is not an issue as it will not be serialized when sending the response back to Alexa. Further, this change would break the (super edge case, mind you) of someone having set a card and then wanting to blow it away from the response by explicitly setting it to null. It is this latter case of potential breaking behavior, rare though it may be, that gives me some pause to accept the change. Let me know what you think.

**Comment by kkocel** [comment]
Main reason why I submitted this PR is case when I pass `null` directive. When I do this, following part results in NPE:

```java
        for (Directive directive : directiveList) {
            if (directive.getType().equals("VideoApp.Launch")) {
                return true;
            }
        }
```

If we want to accept nulls as parameters then preceding code should be refactored then.

As a side note - maybe you could consider using JSR-305 nullability annotations? It would help greatly with Kotlin interoperability as well as with IDEA code hints. More info here: https://blog.tlinkowski.pl/2019/when-to-use-jsr-305-for-nullability-in-java/

**Review by pbheemag — COMMENTED** [review]
Thanks for the PR. The null check for the directive makes sense but a null check for the card doesn't add much value to the existing workflow. Could you kindly update the the PR to just have the null check for the directive so that we can get this merged. As Jonathan mentioned, `A null card being attached is not an issue as it will not be serialized when sending the response back to Alexa. `

**Comment by kkocel** [comment]
@pbheemag what I did instead I've just added null directive check in condition wether directive has certain type:
```java
        for (Directive directive : directiveList) {
            if (directive != null && directive.getType().equals("VideoApp.Launch")) {
                return true;
            }
        }
```

**Review by pbheemag — APPROVED** [review]

**Pull request merged**
