### PR TITLE
Fix typos in README.md

### PR DESCRIPTION
**Pull request by jaferkhan**
## Description
This pull request fixes two typos that are present in the existing README markdown file of the maven project `ask-smapi-sdk`

## Motivation and Context
When I tried to use this library, I copied code straight from the `usage` section without any forethought and thought that it would work as expected. However, the code didn't work. At first, I thought I had done some wrong but when I took a closer look, I found a typo inside the code. And I also noticed another typo upon closer reading. And so this pull request fixes them.

## Checklist
- [ ] My code follows the code style of this project
- [x] My change requires a change to the documentation
- [x] I have updated the documentation accordingly
- [x] I have read the **README** document
- [ ] I have added tests to cover my changes
- [ ] All new and existing tests passed

## License
- [x] I confirm that this pull request can be released under the Apache 2 license

### CODE REVIEW

**Comment by pbheemag** [comment]
Hi @jaferkhan ,
Thank you for noticing the issue and fixing it promptly. Kindly squash multiple commits in this PR into a single commit to keep the commit history clean. I'll merge this PR once it is done.

**Review by nikhilym — APPROVED** [review]
:shipit:

**Review by pbheemag — APPROVED** [review]

**Comment by pbheemag** [comment]
Hi @jaferkhan ,
Thank you for noticing the issue and fixing it promptly. I'll go ahead and merge this PR. Keep supporting our SDK.

**Comment by jaferkhan** [comment]
You're most welcome. Sure, I would love to ^_^

**Pull request merged**
