### PR TITLE
[ci] Correct maven build as directory structure was completely wrong

### PR DESCRIPTION
**Pull request by hazendaz**
Based on other community feedback on other PRs seems this will go no where.  However this purely fixed the build just by properly putting files where they belong.  So if nothing else, please fix the build on master even if someone internal to amazon does it.

### CODE REVIEW

**Comment by rvanderwerf** [comment]
I don't think the target dir should be in there with the windows paths?

**Comment by hazendaz** [comment]
Oops...probably was missing git ignore and I didn't notice.  I'll fix it tonight.  Only changes where meant to more directories.  Thanks for catching that.

Get Outlook for Android<https://aka.ms/ghei36>


________________________________

**Comment by hazendaz** [comment]
Added ignore for maven target directory and squashed commit.

**Comment by ZongwanAmz** [comment]
Added a sourceDirectory tag in pom.
The current folder structure can be used with mvc compile now.

**Comment by hazendaz** [comment]
ok - thanks.

**Pull request closed without merging**
